### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by Ylowe** [SolutionGuidance/psm#1030]
I was looking to get a peek into the source code regarding specifying the database which the app draws information from, and how the app queries information from the database. I can't seem to find it in the psm-app anywhere. Any further information about the source code organization or the database architecture would be extremely helpful. 

Thank you!

**Comment by jasonaowen** [comment]
This is a pretty broad question. I will try to answer it, but it would help if you shared the problem you were trying solve, and what you've attempted so far. These kinds of questions are also more easily solved interactively; I suggest you [join our Zulip server](https://chat.opentechstrategies.com/#narrow/stream/Provider.20Screening) and ask in the "Provider Screening" stream.

The PSM relies upon WildFly for providing connections to the database. See the [database configuration section of the install docs](https://github.com/SolutionGuidance/psm/blob/master/INSTALL.md#configure-database) for more detail. The PSM is hard-coded to look for two data sources, named `TaskServiceDS` and `MitaDS`; both must be configured in WildFly, and may point to the same PostgreSQL database.

Queries are generated by Hibernate, an object-relational mapping tool, which fulfills the Java EE persistence API. The `@Entity`s defined in the PSM are all in the [`gov.medicaid.entities` package](https://github.com/SolutionGuidance/psm/tree/584287df0cb30348370a21a4cb36016e8e64cc43/psm-app/services/src/main/java/gov/medicaid/entities); generally, the persistence-related code should all be contained in the `cms-business-process` subproject.

Does this help, @Ylowe?

**Comment by Ylowe** [comment]
Hi Jason,

This helps tremendously. Thank you so much!

Yang

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
