### ISSUE TITLE
Remove "Lorem Ipsum" text wherever possible.

### ISSUE THREAD

**Issue by kfogel** [SolutionGuidance/psm#108]
Making this a separate issue (disentangling from issue #51).

Branch [51-remove-lorem-ipsum](https://github.com/opentechstrategies/psm/tree/51-remove-lorem-ipsum) has progress so far.  I think that branch is out-of-date now anyway, especially after the issue #53 changes were merged in PR #54.  So I'll make a new branch, basing its name on this new issue number, port over anything from the original branch that needs to be ported over, and create a PR from there.

**Comment by jasonaowen** [comment]
I still count 3 instances of this:

- [external_home.jsp, line 33](https://github.com/OpenTechStrategies/psm/blob/a8cd80a143ec6beb43e99729abbe118594d2a6fc/psm-app/cms-web/WebContent/WEB-INF/pages/provider/dashboard/external_home.jsp#L33-L40)
- [external_home.jsp, line 61](https://github.com/OpenTechStrategies/psm/blob/a8cd80a143ec6beb43e99729abbe118594d2a6fc/psm-app/cms-web/WebContent/WEB-INF/pages/provider/dashboard/external_home.jsp#L61-L68)
- [profiles.jsp, line 89](https://github.com/OpenTechStrategies/psm/blob/a8cd80a143ec6beb43e99729abbe118594d2a6fc/psm-app/cms-web/WebContent/WEB-INF/pages/provider/onboarding/profiles.jsp#L89-L96)

None of them are really in enabled areas, as they have to do with linking to external accounts, so deleting them should be low-risk.
