### ISSUE TITLE
Split BeneficialOwnership subclasses into their own Tables

### ISSUE THREAD

**Issue by BenGalewsky** [SolutionGuidance/psm#139]
BeneficialOwnership entity has two subclasses, PersonBeneficialOwner and OrganizationBeneficialOwner.

There is one table that has the union of the fields needed for this. We kept that as is for expediancy in converting over to H5, but single-table inheritance is not as clear as joined table inheritance, and is not consistent with Entity and its derivatives. 

Please update the table and change these classes.

Progress on #36 and comments from PR #133

**Comment by jasonaowen** [comment]
The server log contains warnings on startup:

```
15:49:24,440 WARN  [org.hibernate.cfg.AnnotationBinder] (default task-7) HHH000133: Discriminator column has to be defined in the root entity, it will be ignored in subclass: gov.medicaid.entities.OrganizationBeneficialOwner
15:49:24,445 WARN  [org.hibernate.cfg.AnnotationBinder] (default task-7) HHH000133: Discriminator column has to be defined in the root entity, it will be ignored in subclass: gov.medicaid.entities.PersonBeneficialOwner
```

Splitting into tables should also fix these warnings.
