### ISSUE TITLE
View Enrollment Details confirmation screen: contact name & email address are blank

### ISSUE THREAD

**Issue by brainwane** [SolutionGuidance/psm#161]
After a provider's created an enrollment, on the "View Enrollment Details" confirmation screen, "Contact name" & "Contact email address" are blank when they should not be. (I checked the "Same as Above" checkbox on the "Personal Info" screen, while enrolling.)

![view-enrollment-details](https://user-images.githubusercontent.com/842790/27238476-031b9fb6-529b-11e7-8b58-644affcab2a0.png)

**Comment by brainwane** [comment]
This issue also happens in the PDF export -- there's no information in the "Contact Information" section.

**Comment by jasonaowen** [comment]
The two options we considered to address this problem are to replicate the provider details into the contact info section when the "same as above" checkbox was checked, or to simply remove the contact info when that checkbox is checked. The former would involve a bit more effort, as we'd have to conditionally extract the provider information.

@jvasile and I decided that simply removing the contact info section when the "same as above" checkbox is checked is what we'll do.

See also [the chat discussion on Zulip](https://chat.opentechstrategies.com/#narrow/stream/6-Provider-Screening/subject/new.20dev/near/43139).
