### ISSUE TITLE
dropdown menus too short and narrow

### ISSUE THREAD

**Issue by brainwane** [SolutionGuidance/psm#163]
![provider-type-too-small](https://user-images.githubusercontent.com/842790/27238684-d720e500-529b-11e7-8e42-578360d9bc8c.png)

In several places in the provider enrollment workflow, the application displays a dropdown menu whose height is too short and cuts off the bottom of the letters in the value chosen.

I'm using Firefox 45.9.0 on Debian.

**Comment by cecilia-donnelly** [comment]
This is behaving better for me.  Have others seen this improve?

**Comment by jasonaowen** [comment]
@brainwane: is this still an issue for you?

**Comment by brainwane** [comment]
![cut-off-descender](https://user-images.githubusercontent.com/842790/31359450-0fbdd996-ad18-11e7-9a50-19fa2803043c.png)

Yeah, descenders (see the `p` in "Optometrist" in this screenshot) still get truncated.

**Comment by jasonaowen** [comment]
Aha, thanks, I see it too at most zoom levels. It looks like we're using a fixed height for the element: https://github.com/OpenTechStrategies/psm/blob/master/psm-app/cms-web/WebContent/css/style.css#L963 .

**Comment by brainwane** [comment]
![truncation-dropdown](https://user-images.githubusercontent.com/842790/32192546-dedc0734-bd8a-11e7-977e-02a1ac34e295.png)

I just noticed that the dropdown is also too narrow.

**Comment by brainwane** [comment]
Still an issue on master as of today.
