### ISSUE TITLE
Remove/edit code pointing to old external-sources app

### ISSUE THREAD

**Issue by cecilia-donnelly** [SolutionGuidance/psm#165]
The external sources source code is obsolete and was deleted in #68, closing #11.  However, there are still references to it, as in #143.  As we set up a new connection to federal data sources (e.g. building on #67), we'll need to remove and/or edit the code that points to the old `ext-sources` app.

Waffle Epic metadata:
parent #773
parent #788
parent #776
parent #764
parent #769
parent #777
parent #796

**Comment by brainwane** [comment]
We should also rewrite or delete the part of `DESIGN.md` that talks about `ext-sources`.

**Comment by cecilia-donnelly** [comment]
We are connecting to another external source soon and will need to remove the obsolete references to it in the application.
