### ISSUE TITLE
Exporting enrollment to PDF: "Remittance Sequence" not substituted in

### ISSUE THREAD

**Issue by brainwane** [SolutionGuidance/psm#167]
I'm logged in as a provider. I go to view my enrollment details (on http://localhost:8080/cms/provider/enrollment/jump?page=Provider+Statement ) and export the PDF.

In the "Practice Information" section:

"Remittance Sequence: PATIENT_ACCOUNT_OR_OWN_REFERENCE_ORDER "

**Comment by cecilia-donnelly** [comment]
This was finished by @HemKal in PR #848.
