### ISSUE TITLE
Don't display # field or empty Specialty field in PDF export of enrollment

### ISSUE THREAD

**Issue by brainwane** [SolutionGuidance/psm#168]
I'm logged in as a provider and I've submitted an enrollment as an acupuncturist (which does not allow me to submit a specialty). I go to view my enrollment details (on http://localhost:8080/cms/provider/enrollment/jump?page=Provider+Statement ) and export the PDF.

In the "License Information" section, there's a "#" column (value: "1", probably the ID number of this enrollment in the local database - unnecessary to display, in my opinion), and a "Specialty" column (value: blank - unnecessary to display, or we should explicitly say "None").

**Comment by frankduncan** [comment]
The # field currently matches what appears on the website, which is just the displayed table row.  Not sure if it should be removed.

The specialty field is definitely inappropriate here, since there's a whole different set of licenses for specialties.
