### ISSUE TITLE
Polish & speed up Javadoc gh-pages publication

### ISSUE THREAD

**Issue by brainwane** [SolutionGuidance/psm#255]
From @jasonaowen's comment on #249:

> I would like to suggest an alternate approach. This is a bigger request than the rest, and it affects only the performance and readability and not the functionality, so please consider it optional.

> 1. We start out in a clone of our repo already, which Travis checks out on our behalf. I believe the variable [`$TRAVIS_BUILD_DIR`](https://docs.travis-ci.com/user/environment-variables) contains the location of that checkout, or you can just `cd ..` to get out of the `psm-app` subdirectory.

> 2. The API docs are generated in a build directory, which is ignored by `.gitignore`. The `gh-pages` branch does not have a `psm-app` directory, so switching branches leaves those built files behind.

> 3. `git push` [allows pushing to a URL](https://git-scm.com/docs/git-push#git-push-ltrepositorygt)

> Given all that, I think all we need do is switch branches, move the docs from `psm-app/build/reports/api-docs`, add them as usual, commit, and push to the URL above. This lets us avoid a duplicate checkout of our fairly sizable repository, and the time and potential network issues associated with it.

Putting this here so we can merge #249 but still pursue improvements per #30.

**Comment by jasonaowen** [comment]
Given the decision to move GitHub Pages docs generation out of Travis and into a manual task ([recorded in a comment](https://github.com/SolutionGuidance/psm/pull/478#issuecomment-353651083) on #478), these suggestions are no longer relevant. Closing.
