### ISSUE TITLE
Complete or remove the ability to suspend user accounts

### ISSUE THREAD

**Issue by jasonaowen** [SolutionGuidance/psm#33]
There is an attribute of a user, `status`, which can be either `ACTIVE` or `DISABLED`. New users default to `ACTIVE`, there is no UI that I can find that allows the status to be altered, and AFAICT nothing ever reads this value.

Why is it here? Do we still want it? Either fully implement the ability to suspend an account, or remove the dead code and unused database column.

**Comment by brainwane** [comment]
I wonder whether #327 would use this.

**Comment by PaulMorris** [comment]
Seems related to this requirement: `psm-AD-5.14`  "The PSM shall support the state policy to disable account due to invalid login attempts."
