### ISSUE TITLE
Registration Page name order is inconsistent

### ISSUE THREAD

**Issue by jvasile** [SolutionGuidance/psm#375]
If we're going to ask for first, middle, and last names on the /cms/accounts/new page, we should put the fields in that order.  Right now it's last, first, middle, which... [derp](http://www.woodweb.com/knowledge_base_images/bah/metric-versus-imperial_02.png).

**Comment by cecilia-donnelly** [comment]
This occurs in multiple places: the self-registration page, the "create new user" and "edit user" pages available to a system admin, and anywhere user details are displayed.  The quick fix is just reordering these in each place.  The more complete fix is, as usual, extracting this to a jsp fragment which can be included everywhere it is needed.

Most of the provider pages already use "First, Middle, Last."  This other order appears to be used only for user accounts.

**Comment by cecilia-donnelly** [comment]
However, in table headers and search results, the PSM frequently asks for "Last Name, First Name."  Do we also want to reorder that?  I think starting with last name is probably appropriate in those cases.

**Comment by cecilia-donnelly** [comment]
Fixed in #683.
