### ISSUE TITLE
configurable contact page for reaching state Medicaid office

### ISSUE THREAD

**Issue by brainwane** [SolutionGuidance/psm#389]
[From](https://github.com/OpenTechStrategies/psm/pull/382#discussion_r135869007) @kfogel, regarding a "Please speak with the state Medicaid office" instruction in the user documentation:

> Can we file an issue associated with this last sentence, about having a configurable contact page for reaching the state Medicaid office? E.g., psm.example.com/contact or something like that, which is configured differently for each state or territory where the PSM is installed. Then this text could link to that page.

**Comment by brainwane** [comment]
@kfogel [continued](https://github.com/OpenTechStrategies/psm/pull/382#discussion_r135869741):

> (By the way, that contact page should also have some gateway to the PSM project itself for reporting bugs; that is, we don't want the state Medicaid office to have to filter all bug reports -- we should give interested users a way to get to the source project directly if they want to, as long as the existence of that way is not too distracting for the vast majority of users who won't ever need it.)

**Comment by brainwane** [comment]
Once we address this, we should update the documentation in `docs/userhelp/`.

**Comment by brainwane** [comment]
Also this fix should be applied to `psm-app/cms-web/WebContent/WEB-INF/pages/accounts/register_success.jsp`, as a replacement for the link in:

`If you do not receive the email within a reasonable amount of time, please <a href="#">contact us</a>`

**Comment by kfogel** [comment]
Closing as a dup of the more general issue #404.
