### ISSUE TITLE
Upgrade iText to a version >5, or use OpenPDF

### ISSUE THREAD

**Issue by cecilia-donnelly** [SolutionGuidance/psm#392]
Older versions of iText have [license issues](https://developers.itextpdf.com/question/versions-older-than-5) (thanks for finding this out, @jasonaowen).  Currently we use iText version 2.1.7, which requires us to purchase a license to avoid possible problems.

@jvasile should take a look at their announcement, and we should upgrade iText.  

@jasonaowen, can you add a comment describing how we're using iText?

**Comment by jasonaowen** [comment]
We use iText everywhere we generate PDFs, such as the "Export to PDF" button shown on an enrollment view:
![export](https://user-images.githubusercontent.com/1494855/30181282-b863091e-93e0-11e7-86e7-b58ea022665b.png)

It also shows up on the list of enrollments (the tab, not the dashboard), both to export the list and as a link to export each enrollment in the list. There may be other places, as well.

From my reading, it sounds like versions of iText newer than 2.1.7 are released either under the AGPL or are purchased. Are we okay with either of those options for this project? If not, we'll probably want to switch to a different library; after a very brief survey I found [Apache PDFBox](https://pdfbox.apache.org/), which of course is available under the Apache License.

I haven't compared PDFBox's API with iText's, but we have a little bit of abstraction in place which might ease switching. To get a sense of scale, we're using iText in 13 classes (search for `lowagie`).

**Comment by jvasile** [comment]
I won't say what I think of that license announcement in a public forum.  I'm ok with us using 2.1.7 at this point.  There is, however, a maintained fork under MPL at https://github.com/LibrePDF/OpenPDF.  @jasonaowen, we should switch to it if it suits our purposes.  Does it do what we need?

Thanks much.
