### ISSUE TITLE
Decide whether to repair or delete help topics system

### ISSUE THREAD

**Issue by brainwane** [SolutionGuidance/psm#396]
Per @jasonaowen in https://github.com/OpenTechStrategies/psm/issues/195#issuecomment-314795045 , we need to decide whether to repair and use, or delete, the help topics system.

> I reviewed the help system in more depth today. We already knew it was incomplete; users cannot see help items admins create. Finishing that implementation is possible, but may not be the most effective use of our time.

> The help system stores its help items (as it calls them) in the database. This allows for admins to create, edit, and delete topics at runtime. This may be useful for state-specific topics, but topics that all states need would have to be included in the seed data.

> Seeding help items is fine, but such seeded help topics are not great for contextual help: we should be careful about providing a help link next to, say, a disclosure question that goes to a dynamic help page - admins could accidentally delete it, thinking it unnecessary in their environment, and be unable to restore it; there are few things more frustrating than clicking on a help link and receiving a 404 error. If we're seeding the data, and hardcoding links, it would be simpler to just write contextual help directly instead of building and using our own custom CMS.

> On the other hand, maybe it really is useful to allow each state to customize its help documentation, and it is worth hardening pre-seeded help items against deletion. If we're providing separate docs for providers and admins, we would also want to build access controls around help topics. This is doable; we have examples of similar pages and patterns in the application.

**Comment by cecilia-donnelly** [comment]
@jcunard points out some more bugs in the current help system [on the list](https://groups.google.com/forum/#!topic/psm-dev/Mpe_YkpRwag):

- When help topic is saved the Edit/Delete function appears  at first but when you go back to the Help Topics alphabetical list and click on the topic, the option to edit or delete doesn’t appear.
- Got booted out of PSM when I clicked on Edit button, the Delete button works
- Key word Search does not display Help Topics

**Comment by cecilia-donnelly** [comment]
I spoke to @chj124 yesterday and he said it was unlikely that state users would need to create new state-specific help topics.  Given that, we can remove this partially-implemented area of the codebase and integrate help as in #422 and #405.

**Comment by cecilia-donnelly** [comment]
It's possible that in the future we might want to allow state users to edit help documentation.  However, we do not want to have two or more separate help systems.  The work we're currently doing in #422 and #405 is all about harmonizing the help/FAQ docs with the in-app help text.  Any future input from state users should be included in that central system.  I'll close this and open another for removing the incomplete "help topics" portion of the application.
