### ISSUE TITLE
Language: "enrollment" or "application"?

### ISSUE THREAD

**Issue by brainwane** [SolutionGuidance/psm#399]
Currently, we mostly refer to "enrollments" in the user-facing messaging of the PSM:

> New Enrollments

> You can now begin the enrollment process.

> Create New Enrollment

@kfogel [pointed out](https://github.com/OpenTechStrategies/psm/pull/382#discussion_r135871331) that many users will think in terms of "applying" and creating an "application" rather than creating an "enrollment". What language should we use, and should we use different language for providers than for other types of users?

**Comment by brainwane** [comment]
I just spoke with @jasonaowen about the technical work needed if we decide to make this change.

He pointed out: for good maintainability, we'd want to not only change the user docs and the user messaging, but the variable, class, table, column, etc. names throughout the codebase. Otherwise it'd get confusing to discuss "applications/applying" as implemented by code referring to "enrollments/enrolling". Some of that is automatable or semi-automatable, especially with IntelliJ's tools, but some is not, and so it'd be a nontrivial technical task.

**Comment by cecilia-donnelly** [comment]
I asked one state about this and they said they say "application for enrollment."  Not sure if that helps!

**Comment by brainwane** [comment]
@chj124 offered [some more insight on this question](https://github.com/OpenTechStrategies/psm/pull/410#issuecomment-335786210) with **three** steps

* application
* approval
* enrollment

**Comment by PaulMorris** [comment]
This and issue #485 are duplicates.  I'm closing this one since it is framed as a question, and we have the answer.  "Application" is the more accurate term, so we should use it rather than "Enrollment".
