### ISSUE TITLE
Add a "do you accept EFT" checkbox

### ISSUE THREAD

**Issue by cecilia-donnelly** [SolutionGuidance/psm#411]
We have a requirement to flag providers that accept Electronic Funds Transfer.  This should be a new checkbox on the enrollment form.

We should *not* be accepting information like bank routing numbers or account numbers.  That will be the provider management module's responsibility.

**Comment by jasonaowen** [comment]
Do you have a particular spot in mind? I would imagine next to the billing / reimbursement address on the practice page. I expect that this will apply to both individual and group providers?

**Comment by cecilia-donnelly** [comment]
Ah, that's a good spot for it.  And yes, as far as I know this should apply to all providers.

**Comment by cecilia-donnelly** [comment]
Hmm, I see that providers in private practice already have an input field for "EFT Vendor Number," which isn't required.  I think that must be MN-specific -- it might imply that the original designers planned to use it to link to a record in some other system.  

@PaulMorris, my instinct here is to remove the EFT Vendor Number field and replace it with a "do you accept EFT?" question and associated checkbox.  Thoughts?

**Comment by PaulMorris** [comment]
@cecilia-donnelly Yeah, that makes sense to me, if it's not required.

**Comment by PaulMorris** [comment]
PR #531 converts the previously existing EFT number to an EFT boolean value, with tests and UI changes to match.  It does not add any new places in the UI to set this new EFT boolean, but only converts the existing places where the EFT number could be entered (namely in private practice applications).  Adding additional "Do you accept EFT?" questions in other places remains to be done as a follow-up step.

**Comment by cecilia-donnelly** [comment]
Closing this -- we can reopen or add another issue if we want EFT for group/organizational applications.
