### ISSUE TITLE
Verify that we accept EIN *or* SSN

### ISSUE THREAD

**Issue by cecilia-donnelly** [SolutionGuidance/psm#412]
Group practitioners should be identified by EIN and individuals should be identified by SSN.  I believe this is already the case, but we should verify that it works in all cases.  Our requirements point out that some group practices may bill individually, in which case we should identify the providers by SSN.

**Comment by jasonaowen** [comment]
[Employer Identification Numbers](https://en.wikipedia.org/wiki/Employer_Identification_Number) are the same length as Social Security Numbers. Neither have check digits, and currently we do no further processing or validation on either.

I think we automatically meet this requirement. @cecilia-donnelly can you say more about what you want to verify, and how?

**Comment by cecilia-donnelly** [comment]
Hmm, right.  I think it's more about giving the fields the right labels and checking that all workflows have a space for the TIN, whether it's an EIN or an SSN.  

In very detailed points, at least sometimes we add the "-" in the EIN, which is in a different place than it is for SSNs:

![ein-hyphen](https://user-images.githubusercontent.com/1497818/31033353-4f16fbae-a525-11e7-98a0-dd60ea1d3904.png)

**Comment by cecilia-donnelly** [comment]
All provider types can enter the tax ID they need.  If we find that this isn't true in the future, we can open a specific issue for that provider type.
