### ISSUE TITLE
Create and/or document session lock after a given period of inactivity

### ISSUE THREAD

**Issue by cecilia-donnelly** [SolutionGuidance/psm#414]
After `n` minutes of inactivity (with configurable `n`), lock the logged-in user's session and require them to re-log-in.  Logging in should take them back to the page they were on.

I believe we currently have some kind of cookie/session expiration that automatically logs out a user after a given period, but I don't know if it's tied to (in)activity.

See also #398.

**Comment by cecilia-donnelly** [comment]
- in `psm-app/cms-web/WebContent/WEB-INF/web.xml`, the `session-timeout` is set to 30 minutes.
- According to [GroupKT docs](http://www.groupkt.com/post/7ee95bbd/session-timeout-handling-in-java.htm), "Session time out kills the session only if time gap between two concussive request is more then the configured time."  So, if a person is actively using the app they won't be logged out while in the middle of filling out an enrollment or similar.

I don't know (yet) how to redirect the user back to the page they were on when they re-login, but that's more of a "nice to have."  It seems like we're most of the way there on this one.

**Comment by chj124** [comment]
the States general security guidance is logout after 15 mins, so as long as its configurable were good

to return them, you will have to track where their at (once logged in). many sites do this, and as with mobile, updates to entered info should happen at time of entry so state is saved

**Comment by cecilia-donnelly** [comment]
Documented and merged; closing this now.
