### ISSUE TITLE
Error when a provider submits an enrollment

### ISSUE THREAD

**Issue by cecilia-donnelly** [SolutionGuidance/psm#419]
On at least one occasion, we ran into a bug where, when a provider user filled out an enrollment and hit "Submit," the enrollment was not submitted and the provider got a "Server Error" instead of the popup saying "The enrollment has been successfully submitted."  This happened with two different provider accounts.  The *admin* account, however, was able to submit the enrollments after logging in.

This was on my local setup, which was idiosyncratic in that I had manually reset the status of the enrollments in question to "draft" (in a `psql` shell, by running something like `update "enrollments" set "enrollment_status" = '01';`).  I don't remember if they had already been reviewed when I reset them.  If so, that might have been the source of the problem.  I'd manually reset statuses before without this problem, but perhaps those enrollments were only "pending."  I'll investigate.

**Comment by jasonaowen** [comment]
We seem not to have encountered this again in the last nine months. We've since improved our "server error" page to actually show the underlying error with #831. If any of us get errors while submitting an enrollment, we should file a new issue with the relevant stack trace.
