### ISSUE TITLE
Central documentation site should refer to how it's generated.

### ISSUE THREAD

**Issue by kfogel** [solutionguidance/psm#482]
We now have auto-built documentation at https://opentechstrategies.github.io/psm/, coming (I think) from the `gh-pages` branch in this repository.  Still, that doc site should point to some documentation about how the site itself is built, so that if people want to contribute to it, they can.

This is discussed more starting [here](https://chat.opentechstrategies.com/#narrow/stream/Provider.20Screening/subject/user.20documentation/near/784).

**Comment by brainwane** [comment]
Fixed in 51d757e43f0c3319151da51d122ffef8d1c799f5 .
