### ISSUE TITLE
Do not run Serenity tests on external PRs

### ISSUE THREAD

**Issue by jasonaowen** [SolutionGuidance/psm#555]
We run our Serenity/Selenium tests with the help of Sauce Labs. Using their service requires account information, which we encode in [Travis secured environment variables](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings). [The Travis docs say](https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions)

> Travis CI makes encrypted variables and data available only to pull requests coming from the same repository. These are considered trustworthy, as only members with write access to the repository can send them.

We should disable the Serenity tests when the encrypted variables are unavailable, so that pull requests from external repos have a chance at passing.

**Comment by cecilia-donnelly** [comment]
This will be handled by Jenkins' built-in options after #629.

**Comment by cecilia-donnelly** [comment]
Currently, we are not running CI on PRs from external contributors.  That means that if someone without "write" permissions (someone not on the core team) forks this repository and submits a PR, Jenkins will not run the tests on that PR (right, @jasonaowen).  However, we can tell Jenkins that the PR is safe and that it should run the various build/test tasks on it.

**Comment by cecilia-donnelly** [comment]
The only thing remaining before we can close this issue is setting up and documenting a way to tell Jenkins to run tests on external PRs.

**Comment by cecilia-donnelly** [comment]
@jasonaowen Is this covered in your Jenkins documentation?  What remains to be done?

**Comment by cecilia-donnelly** [comment]
Documented in #677.
