### ISSUE TITLE
Missing "current tab" indicator on several pages

### ISSUE THREAD

**Issue by jasonaowen** [SolutionGuidance/psm#569]
The PSM used to show which tab the current page was on in its navigation bar. See, for example, the small black down arrow under "My Profile" on the service admin's profile page - the only place they still work:

![screenshot of the service admin's profile page, to demonstrate the small black down arrow under "My Profile"](https://user-images.githubusercontent.com/1494855/33859488-2683d688-dea2-11e7-86ea-65575ab58513.png)

These were lost by accident as [part of our transition to Handlebars](https://github.com/solutionguidance/psm/pull/538#discussion_r156232946). We should restore them, or if they don't matter, remove them entirely.

**Comment by PaulMorris** [comment]
Thanks for catching this @jasonaowen .  Here's the the html output for one of these tabs with the down-arrow:
```
                    <li class="active">
                      <a href="/cms/system/user/list">USER ACCOUNTS</a>
                      <span class="arrow"></span>
                    </li>
```
