### ISSUE TITLE
Use HTML5 instead of XHTML

### ISSUE THREAD

**Issue by cecilia-donnelly** [SolutionGuidance/psm#613]
Using HTML5 will allow us to use built-in placeholder text (c.f. #612) and other modern features.  We can add more advantages to this issue as we come across them -- there may be some changes related to the accessibility work, as well.

@jasonaowen points to this [reference article](http://oli.jp/2009/html5-structure4/).

**Comment by PaulMorris** [comment]
The `onclick` attribute is part of HTML5 but not XHTML.  This came up recently while working on [getting buttons to call JS functions](https://stackoverflow.com/questions/1947263/using-an-html-button-to-call-a-javascript-function/1947531#1947531).  We may or may not want to use `onclick`, but this is one instance where XHTML limited our options (for better or worse).
