### ISSUE TITLE
Use Jenkins for continuous integration

### ISSUE THREAD

**Issue by cecilia-donnelly** [SolutionGuidance/psm#629]
We've been discussing when to move away from Travis for a while, for the following reasons:

1. Travis CI is a proprietary service.  We prefer not to depend on proprietary services.
2. Jenkins allows us to set up scripts and infra about our CI outside of this repository.  One specific CI setup will not be applicable to other groups who want to use this repository, so it's better to separate it from the application code itself.
3. Fix our unreliable Wildfly deployment on Travis (see #304).  (This has been resolved, but could come up again.)
4. Fix our unreliable connection to Sauce Labs on Travis (see #533), by running the integration tests on the Jenkins server.  This also removes another dependency on a proprietary service, since we wouldn't need to use Sauce Labs anymore.
5. Ability to split our CI checks into separate streams, e.g., as @jasonaowen put it "separate, parallel CI checks - splitting linting, and unit tests, and integration tests, and building, and whatever else into separate jobs that each run on a new PR."  This would be easier with Jenkins, and would allow us to more easily see the difference between "this PR breaks a feature" and "this PR has style problems."
6. Run some updates on a regular, but not every PR, cycle.  Most immediately, this refers to things like updating the GitHub Pages site, as in PR #445.  We don't need a new copy of the generated files for every PR, but the site needs to be kept up-to-date.  Doing this weekly or similar would be easier with Jenkins.
7. Keep and publish Serenity reports more easily, as in #266.

I'm sure there are others -- please add them here.

**Comment by cecilia-donnelly** [comment]
@jasonaowen, thanks for this!  Can you write up some documentation of how you set this up?

Presumably someone would need an account to make changes to run permissions, e.g. for #555?

**Comment by jasonaowen** [comment]
Things we still need to do:

- Set up an application token for a bot user, so that Jenkins' ability to mark PRs as passed/failed is not tied to my account
- Set up email, so that Jenkins can email users when builds fail, and so that we can get security update notifications

**Comment by cecilia-donnelly** [comment]
@jasonaowen and I (mostly Jason) are currently working on setting up a bot user to manage PRs in Jenkins.

**Comment by cecilia-donnelly** [comment]
@jasonaowen, do you think we're ready to turn off Travis now?

**Comment by jasonaowen** [comment]
@cecilia-donnelly yes, I think so! I'll work on that shortly.

**Comment by jasonaowen** [comment]
Okay, there are a few more things we still need to do:

- Set up email, so that Jenkins can email users when builds fail, and so that we can get security update notifications.
- Set up webhooks in the PSM repo, so that GitHub notifies Jenkins of events rather than Jenkins polling GitHub.
- Set up a job that deploys to `testing.psm.solutionguidance.com` (and document it alongside the other jobs).

**Comment by jasonaowen** [comment]
@cecilia-donnelly and I worked together this morning to set up webhooks, and we set up email earlier this week. The only remaining thing is deploying to `testing.psm.solutionguidance.com`!
