### ISSUE TITLE
Reliance on JavaScript for form submission may affect many pages.

### ISSUE THREAD

**Issue by kfogel** [SolutionGuidance/psm#65]
Not sure if this is a bug yet, but it might be:

The situation described in issue #40, in which hitting Enter was made to work on the login page through JavaScript associated with an `<a>` element rather than through a proper HTML form button, may affect other pages on the site -- and this method of form submission may have accessibility implications.  Filing this issue so we don't forget to look into this.

**Comment by jasonaowen** [comment]
Another example: the system admin create user page.

**Comment by cecilia-donnelly** [comment]
@PaulMorris, would you say you fixed this by using real buttons instead of links styled as buttons?

**Comment by PaulMorris** [comment]
@cecilia-donnelly , yes, this was fixed by the work in #553 by giving all the forms accessible submit buttons.
