### ISSUE TITLE
Empty link text for providers with no NPI

### ISSUE THREAD

**Issue by jasonaowen** [SolutionGuidance/psm#672]
Some provider types, such as Personal Care Assistants, do not have an NPI. After creating such an enrollment, the dashboard and enrollments pages render that enrollment with an empty link to the enrollment:

![pca-empty-link](https://user-images.githubusercontent.com/1494855/36226993-9501cee8-119d-11e8-90d4-500088c9db5e.png)

This is both a usability problem and an accessibility problem.

We previously addressed a similar case in #573 by making the NPI plain text and moving the link to view the application to the literal string "View", alongside (in that case) "Edit" and "Renew"; in this case it would be next to "Print" and "Export to PDF".

**Comment by PaulMorris** [comment]
This also occurs in the search results tables for both advanced search and quick search.

**Comment by PaulMorris** [comment]
The admin dashboard page has no Actions column, unlike other pages where this is an issue.  So we would need to add an Actions column if we wanted to pursue the same View link strategy on that page.
