### ISSUE TITLE
Action column may wrap to two lines

### ISSUE THREAD

**Issue by PaulMorris** [SolutionGuidance/psm#692]
On service admin "Pending", "Approved", and "Notes" pages content in the action column wraps to two lines:

![screenshot-2018-2-28 enrollment](https://user-images.githubusercontent.com/1091693/36810821-dea037e0-1c99-11e8-987f-9379e1b17b2e.png)

Also can happen on the results of the advanced search page:

![screenshot-2018-2-28 advanced search](https://user-images.githubusercontent.com/1091693/36810676-615f618e-1c99-11e8-8b47-397ec4fe58ad.png)

**Comment by kfogel** [comment]
Raising the importance of this issue and adding a larger screenshot (from the demo server as of today).

![psm-demo-server-2018-08-23-admin-dashboard-pending-enrollments-layout-problem](https://user-images.githubusercontent.com/401111/44542910-c77d7b80-a6d3-11e8-9102-eb1354b0187b.png)
