### ISSUE TITLE
Add writing PR descriptions to CONTRIBUTING.md

### ISSUE THREAD

**Issue by PaulMorris** [SolutionGuidance/psm#703]
Currently our CONTRIBUTING document does not cover writing good PR descriptions, although there are expectations about it.  It would be good to document our practice on this.

**Comment by jasonaowen** [comment]
I agree! I think that the best way to do so is with a template. There's an existing issue for that, so I'm going to close this one. Thanks!

**Comment by jasonaowen** [comment]
Duplicate of #312
