### ISSUE TITLE
Do not reject enrollment on positive provider disclosure

### ISSUE THREAD

**Issue by jasonaowen** [SolutionGuidance/psm#774]
If a provider answers "yes" to any of the provider disclosure questions, we want to reject their application. (right, @cecilia-donnelly?)

![disclosure](https://user-images.githubusercontent.com/1494855/38956949-24c85348-4327-11e8-9dee-913ae525aa9a.png)

We have [code that is supposed to reject such enrollment applications](https://github.com/SolutionGuidance/psm/blob/6650765804b3a2f60acd597352d6eae5194ddbb5/psm-app/cms-business-process/src/main/java/gov/medicaid/process/enrollment/DisqualificationHandler.java#L73), but it currently fails with an exception: [`Cannot change status because it is not in pending state.`](https://github.com/SolutionGuidance/psm/blob/6650765804b3a2f60acd597352d6eae5194ddbb5/psm-app/cms-business-process/src/main/java/gov/medicaid/services/impl/ProviderEnrollmentServiceBean.java#L160)

Verify that we want to reject such applications (instead of preventing them from being submitted), figure out what is setting the enrollment application state to something other than "Pending", and fix the error.

**Comment by cecilia-donnelly** [comment]
Hey @jasonaowen, I don't think we want to reject them out of hand, though it's interesting that we have code to do so.  There are some convictions that cause providers to be excluded for some amount of time: 5, 10 years.  See the [OIG's reinstatement policy](https://oig.hhs.gov/exclusions/reinstatement.asp).  After that period of time they'd have to answer yes to these questions and we'd most likely assign them a higher risk score, but not necessarily exclude them.

**Comment by jasonaowen** [comment]
Aha, interesting! Okay, good, that simplifies things a bit - thank you for that clarification, @cecilia-donnelly. The other side effect of answering "yes" to any of those questions is preventing the LEIE check to happen, since the enrollment is supposed to be rejected - that needs to be fixed.

**Comment by jasonaowen** [comment]
> The other side effect of answering "yes" to any of those questions is preventing the LEIE check to happen, since the enrollment is supposed to be rejected - that needs to be fixed.

Wait, after examining the enrollment business process more closely, I realize that this statement is incorrect. I was conflating it with an earlier validation step.

So, we should just delete the code that automatically rejects (or attempts to, anyway). Do you know how the risk should be affected by answering "yes" to any of these questions, @cecilia-donnelly? We don't currently have any Drools rules that take those answers into consideration.

**Comment by cecilia-donnelly** [comment]
Hey @jasonaowen.  We don't have any rules about more-powerful risk scoring, and I don't quite know how we'll set that up.  We do expect to do better risk-scoring later in the road map, though, including taking things like history of fraud into account.  See RTM items: psm-FR-2.18, psm-FR-2.19, psm-FR-3.2, psm-FR-3.5, psm-FR-3.7, psm-FR-3.9, psm-FR-3.18, psm-FR-3.19.

For now, I don't know what a Drools rule for this would look like.  Do you have ideas?

**Comment by jasonaowen** [comment]
@cecilia-donnelly easy mode would be "if you answer 'yes' to any of these questions, your enrollment application gets a risk value of 'High' assigned".

We could have finer-grained things like "question 1 raises to medium risk, question 3 means high risk, any two answers means high risk", and so on; I would expect that to come from a discussion with states as to how those disclosure questions relate to risk (or even if they still do!).
