### ISSUE TITLE
Add report for mean and median time from submission to review per month

### ISSUE THREAD

**Issue by frankduncan** [SolutionGuidance/psm#794]
From #739, related to #762 

Mean and median time from submission to review by month. Louisiana said this would help them understand the following elements:

* how long it sits in the queue
* how long it takes to review (we don't currently have a way to measure this in the PSM)
*  how long until decision

For us, this is all represented by the same information: time between submission and approval/rejection.

Edit: this report will have a line graph.

**Comment by frankduncan** [comment]
From https://github.com/SolutionGuidance/psm/issues/739#issuecomment-378738452

**Comment by PaulMorris** [comment]
One question for this report is how to count applications that are submitted in one month but reviewed in the next -- namely, which month's mean and median do they count toward?  Also, how to handle applications that have been submitted but not yet reviewed?  Probably just omit not-yet-reviewed applications from the report, so you're only reporting on complete cases (matching pairs of submit and review dates).  

For the first question then, the simplest approach would probably be to count them (applications that span across months) toward the month of the review date.  That way you always have complete pairs of dates to report and the reported data for a previous month wouldn't change as new reviews are completed.  (This is compared with counting them based on the month of the submission date.)

**Comment by frankduncan** [comment]
I think your reasoning toward the first question is good, and so will implement it that way.  For the second, I'll omit for now, but two other ideas would be to calculate based on "if you got everything reviewed today!," or secondly, have a specified "avg time" that we use to give a realistic estimate of what this month might be.

**Comment by frankduncan** [comment]
Also of note, is that we are making an assumption that if they are in approved or rejected status, the last updated time is the time that it was moved to that status.  So it's possible if other code paths update that timestamp due to other updates to enrollments, the report could change.

May make sense to capture that time somewhere, eventually (it could also be that we are capturing it in another table that I don't know about)

**Comment by cecilia-donnelly** [comment]
Notes from states about possible improvements:
- Show mean/median time per admin user, not just top-level (drill down within each month)
- Write up explanation of what month an application appears in (the submitted month or reviewed month?)
- Add a line graph here too (one line for median and one for mean, I expect)
- Keep hours in case time is less than a day!

**Comment by frankduncan** [comment]
Closing this out and opening issues for the improvements from the states.
