### ISSUE TITLE
topcoder RandomStringGenerator

### ISSUE THREAD

**Issue by mwolfthal** [SolutionGuidance/psm#818]
I am seeing a failed reference to com.topcoder.util.keygenerator.random.RandomStringGenerator; didn't see this problem the last time I built the app, a couple of weeks ago.

**Comment by jasonaowen** [comment]
Hi @mwolfthal, welcome to the PSM! Could you please share some more details to help us reproduce this?

1. What command did you use to build the app?
2. What is the full error message?
3. What OS are you on?
4. What version of Java are you using?
5. What commit do you have checked out?

Hopefully that will be enough to diagnose the issue!

**Comment by mwolfthal** [comment]
Windows 7 64-bit

jdk1.8.0_144

 

checked out master.

 

"gradlew  assemble" produces:

 

 

:cms-business-model:xsd-dependency-tree

jaxb: starting Namespace Task

jaxb: generating xsd namespace dependency tree

:cms-business-model:xjc

:cms-business-model:compileJavawarning: [options] bootstrap class path not set in conjunction with -source 1.6

1 warning

 

:cms-business-model:compileGroovy NO-SOURCE

:cms-business-model:processResources

:cms-business-model:classes

:cms-business-model:jar

:cms-business-model:assemble

:services:compileJavaNote: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

 

:services:compileGroovy NO-SOURCE

:services:processResources

:services:classes

:services:jar

:cms-business-process:compileJavaD:\Weichi\projects\ots\psm\psm-app\cms-business-process\src\main\java\gov\medicaid\services\impl\RegistrationServiceBean.java:57: error: package com.topcoder.util.keygenerator.random does not exist

import com.topcoder.util.keygenerator.random.RandomStringGenerator;

                                            ^

D:\Weichi\projects\ots\psm\psm-app\cms-business-process\src\main\java\gov\medicaid\services\impl\RegistrationServiceBean.java:100: error: cannot find symbol

    private final RandomStringGenerator passwordGenerator = new RandomStringGenerator(

                  ^

  symbol:   class RandomStringGenerator

  location: class RegistrationServiceBean

D:\Weichi\projects\ots\psm\psm-app\cms-business-process\src\main\java\gov\medicaid\services\impl\RegistrationServiceBean.java:100: error: cannot find symbol

    private final RandomStringGenerator passwordGenerator = new RandomStringGenerator(

                                                                ^

  symbol:   class RandomStringGenerator

  location: class RegistrationServiceBean

D:\Weichi\projects\ots\psm\psm-app\cms-business-process\src\main\java\gov\medicaid\services\impl\RegistrationServiceBean.java:101: error: cannot find symbol

        RandomStringGenerator.ALPHANUMERIC_SYMBOLS + "~!@#$%^&*()", 8, 8, new SecureRandom());

        ^

  symbol:   variable RandomStringGenerator

  location: class RegistrationServiceBean

Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

4 errors

FAILED

:cms-business-process:processResources

:cms-portal-services:compileJava NO-SOURCE

:cms-portal-services:compileGroovy NO-SOURCE

:cms-portal-services:processResources

:cms-portal-services:classes

:cms-web:compileJava

:cms-web:compileGroovy NO-SOURCE

:cms-web:processResources

:cms-web:classes

:frontend:nodeSetup UP-TO-DATE

:frontend:npmSetup UP-TO-DATE

:frontend:npmInstall UP-TO-DATE

:userhelp:htmlconsole: Failed to install '': java.nio.charset.UnsupportedCharsetException: cp0.

 

Running Sphinx v1.6.3

loading translations [en]... done

loading pickled environment... not yet created

building [mo]: targets for 0 po files that are out of date

building [html]: targets for 8 source files that are out of date

updating environment: 8 added, 0 changed, 0 removed

reading sources... [ 12%] account-help

reading sources... [ 25%] enrollment

reading sources... [ 37%] index

reading sources... [ 50%] process-purpose

reading sources... [ 62%] provider-help

reading sources... [ 75%] service-admin-help

reading sources... [ 87%] service-agent-help

reading sources... [100%] system-admin-help

 

D:\Weichi\projects\ots\psm\psm-app\userhelp\source\enrollment.rst:167: WARNING: Duplicate substitution definition name: "nppes_link".

looking for now-outdated files... none found

pickling environment... done

checking consistency... done

preparing documents... done

writing output... [ 12%] account-help

writing output... [ 25%] enrollment

writing output... [ 37%] index

writing output... [ 50%] process-purpose

writing output... [ 62%] provider-help

writing output... [ 75%] service-admin-help

writing output... [ 87%] service-agent-help

writing output... [100%] system-admin-help

 

generating indices... genindex

writing additional pages... search

copying static files... done

copying extra files... done

dumping search index in English (code: en) ... done

dumping object inventory... done

build succeeded, 1 warning.

:cms-web:war

:cms-web:assemble

:frontend:assemble UP-TO-DATE

:integration-tests:compileJava NO-SOURCE

:integration-tests:processResources NO-SOURCE

:integration-tests:classes UP-TO-DATE

:integration-tests:jar

:integration-tests:assemble

:services:assemble

:userhelp:assemble

 

FAILURE: Build failed with an exception.

 

* What went wrong:

Execution failed for task ':cms-business-process:compileJava'.

> Compilation failed; see the compiler error output for details.

 

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

 

* Get more help at https://help.gradle.org

 

BUILD FAILED in 1m 5s

19 actionable tasks: 16 executed, 3 up-to-date

 

Marvin Wolfthal

email: maw@weichi.com

**Comment by mwolfthal** [comment]
The problem was a missing jar:
psm-app/cms-portal-services/lib/random_string_generator.jar

P.S.: The jar was not named specifically in the build config:
compile fileTree(dir: '../cms-portal-services/lib', include: '*.jar')
