### ISSUE TITLE
Show error on personal email address

### ISSUE THREAD

**Issue by cecilia-donnelly** [SolutionGuidance/psm#842]
As of PR #832, the contact email address will be required (which is a consequence of #341, which uses that email address to send notifications to users).  For individual enrollment applications, the contact email is sometimes autofilled from the "Email Address" input by using the "Same as Above" checkbox.  That "Email Address" field is *not* required in and of itself.

@frankduncan noticed that if a user fills in information, leaving the Email Address input empty (allowed) and checking the "Same as Above" checkbox, the ensuing error is unclear.  The "Same as Above" checkbox means that the Email Address is suddenly required, because it fills the Contact Email field, which is required.  I hope this is comprehensible.

I thought that the thing to do was to add an error to the new Contact Email rule which would change the error text if the "Same as Above" checkbox was checked, so that the red highlighting would appear around the "Email Address" field and the error text would read "Email Address is required when Same as Above is checked."  While doing that, I found that the rules currently don't appear to have any concept of the Email Address field at all, meaning that adding an error reporter on that field has no effect.

I believe that the way to add this element to the rules is by adding it to the "PersonalInformation" fieldset, which appears to be generated from the JAXB "PersonType".  I don't know how to alter these JAXB objects, though.

It would be simpler to do this in Javascript, but I *would* like to be consistent in how we create error messages for users, so the right thing seems to be to handle this in the rules.

**Comment by kfogel** [comment]
Semi-related to issue #1028.
