### ISSUE TITLE
Add authn/authz to FHIR API

### ISSUE THREAD

**Issue by cecilia-donnelly** [SolutionGuidance/psm#847]
I'm splitting this out from #623 so we can more easily track it.

Currently, the API is completely public.  For the first round of controlling who calls the API, we'll have three kinds of access:
- [x] no access at all -- this is a user who has no right to read or write to the API
- [x] read-only access to all information accessible via the API
- [x] read and write access to all information accessible via the API

Note that currently the API only has `GET` endpoints, so there is nowhere for a user to write to.

@slifty, @notpace, @kfogel, and I have begun to have some conversations about future, more complicated, authorization strategies.  These are somewhat related to the user role conversation in #10.

We expect that we will want some kind of business-limited access, where a provider has access to read and write to resources that they "own."  This "ownership" right now would be determined (probably?) by the creator of the resource.  That is, if a provider created an application for enrollment then they'd be considered its owner and would be able to view and edit that application via the API (once the API is sophisticated enough to allow that).  Other modules in the MMIS, meanwhile, should have access to all resources, regardless of owner.

**Comment by notpace** [comment]
Tagging @mbestavros as well
