### ISSUE TITLE
Mean / Median report should use hours in case lapsed time is less than a day

### ISSUE THREAD

**Issue by frankduncan** [SolutionGuidance/psm#897]
From https://github.com/SolutionGuidance/psm/issues/794#issuecomment-390324661

What the title says.  Currently the report just says "0 days" if everything is done quickly, and this could be confused with an error.

**Comment by frankduncan** [comment]
This was already fixed.

**Comment by jasonaowen** [comment]
I believe this was fixed in #819, specifically. (Please correct me if I'm wrong, @frankduncan!)
