### ISSUE TITLE
Abstract risk-scoring functionality behind a formal service definition.

### ISSUE THREAD

**Issue by kfogel** [SolutionGuidance/psm#9]
If the risk-scoring were abstracted behind a service definition, then the PSM would be able to more easily swap different risk-scoring approaches in and out.  It's not clear how much this abstraction already exists in the code, but based on earlier examination I believe it is not completely abstracted.

**Comment by jasonaowen** [comment]
We assign risk levels via [Drools rules](https://github.com/SolutionGuidance/psm/blob/master/psm-app/cms-business-process/src/main/resources/cms.screening.drl#L2130-L2224), which appear to be based on the [risk assignments for Medicare providers](https://www.law.cornell.edu/cfr/text/42/424.518).

I think this is the abstraction level we want; Drools rules are relatively easily changed or replaced, and can be done so on a per-state basis at or after deploy time.
