### ISSUE TITLE
Login page asks confusingly about "Domain"; should either not ask or else ask a clearer question.

### ISSUE THREAD

**Issue by kfogel** [SolutionGuidance/psm#911]
The login page shows word "Domain" as the label for a two-item dropdown.  A provider logging in for the first time wouldn't know how to interpret that -- even I'm not positive I know how to interpret it.  My *guess* is that the two choices "Online Portal" and "MN-ITS" mean, respectively, "provider login" and "state-side admin login", but if so this is hardly a clear way to express that.

![psm-demo-login-page-2018-06-28](https://user-images.githubusercontent.com/401111/42047250-67c97aca-7ac5-11e8-9126-086f5ec786fa.png)

One solution would be to have a radio button or other standard selector by which one can unambiguously know that one is being asked about one's role, and unambiguously answer.  The selector needn't mention the state's name -- its job would just be to find out if you're logging in as a provider or a state-side admin.

But in fact, do we even need a selector for this at all?  Wouldn't this just be a property of the username?  IOW, if you just create a new account via the "Register New Account" link, then by default that is a provider account.  When a new state-side admin account is created, it will be created by an existing state-side admin who has the appropriate superpowers to create such accounts.  IOW, why are we even asking this on the login page?  You could just log in, and the PSM would know who you are and what roles/authorizations you have.

This was originally reported as part of issue #39, but this part is basically a UI issue and can be fixed independently of the rest of issue #39.

**Comment by kfogel** [comment]
Okay, James explained to me what's going on here:

The "Domain" is probably an authorization domain that we may not be able to determine automagically from the username -- because usernames might be unique only within a given domain (unless the PSM enforces otherwise, which is not a decision we've made).  For example, some users might need to authorize against an internal MMIS authn source, others against some agency-specific or group-specific provider database, still others against a state admin LDAP source, etc.

However, the UI could do a better job of making this clear, and of guiding the user to choose the right authn source.

Furthermore, *right now* we're pretty sure Domain isn't being used.  We could just comment out that whole block on the login page template and it'd be fine.  Until we support domains, there's no reason to confuse users with them (and we'll be better able to design the UI when we have the real use case in hand).

So for now, assuming the above is all correct, let's comment out that part of the login page.

**Comment by jasonaowen** [comment]
> Furthermore, right now we're pretty sure Domain isn't being used. ... Until we support domains, there's no reason to confuse users with them (and we'll be better able to design the UI when we have the real use case in hand).

I agree with this! When we're ready to support multiple login methods, we'll understand how that will work and what integrating with those other authentication methods will look like.

> We could just comment out that whole block on the login page template and it'd be fine. 

Let us go further, though, and delete it entirely; the existing code has no special value, and when the time comes, it seems very likely to me that we'll take a different approach. If not, we'll have the current in our version history, and we can dig it out. Let's not leave commented-out code behind in the meantime.

**Comment by frankduncan** [comment]
If you pull on this thread, you may run into external_home.jsp and all the related controller code and whatnot.  I followed it some when working on #906

**Comment by jasonaowen** [comment]
Yeah, this is an easy sweater to unravel! It also has lots of loose threads. We should delete all that unused code, but let's be careful to do so incrementally.

**Comment by PaulMorris** [comment]
I'm closing this now that #922 has removed this feature from the UI.  I've filed #931 as a follow-up issue for dealing with the code backing this feature.
