### ISSUE TITLE
Suggestion about using jCasbin in the AuthZ interceptor

### ISSUE THREAD

**Issue by veotax** [SolutionGuidance/psm#923]
Hi. I found we are adding authorization security to the RESTful API (https://github.com/SolutionGuidance/psm/issues/847) and there's also some related commit here: https://github.com/SolutionGuidance/psm/commit/aa1c15ec87595939469563592f781ea83b94d70c.

It seems that we are looking for a light-weight authorization library. Spring security is too heavy for this scenario.  To avoid re-inventing the wheel, I'd like to recommend: [jCasbin](https://github.com/casbin/jcasbin), which is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in casbin's language) can be persisted in files or database.
4. multiple models like ACL, BLP, RBAC, ABAC, RESTful are supported. For RESTful, you can use the built-in ``keyMatch`` function to match a RESTful path to a pattern like ``/books/*``, or use regex directly.

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

After a glance at your code, I think jCasbin just provides all you need to implement a RESTful interceptor and nothing else is involved. You can see our interceptor examples here: https://github.com/casbin/jcasbin#web-frameworks. In all examples, HTTP basic authentication is used as the authN way, but you can switch to any authentication as you like.

I think jCasbin can be a choice. What do you think? Thanks.

**Comment by jasonaowen** [comment]
Duplicate of #775
