### ISSUE TITLE
./gradlew db:update stuck at 0%

### ISSUE THREAD

**Issue by Ylowe** [SolutionGuidance/psm#985]
Trying to run the ./gradlew db:update command, and it gets stuck at 0% progress. Fixed prior JDBC error by installing blank postgresql 9.4 database. Running on Debian 8. We think it may be a problem with the wrapper, any help or insight would be appreciated.

**Comment by jasonaowen** [comment]
Hi @Ylowe, I'm sorry you're having trouble!

> Trying to run the ./gradlew db:update command, and it gets stuck at 0% progress

Can you share some more details? Does the command eventually complete (including unsuccessfully)? If so, how long does it take? Can you paste the output here?

> Fixed prior JDBC error by installing blank postgresql 9.4 database

How did you install it? How did you configure it? Liquibase - and, later, WildFly - need to connect via TCP/IP, and some distributions of PostgreSQL default to only allowing connections via Unix domain sockets. You can check if TCP/IP connections are allowed by trying to connect via psql: `psql -h localhost -U psm psm`.

**Comment by Ylowe** [comment]
Hi @jasonaowen, thank you for your quick reply!

Regarding the ./gradlew command, it never completes and eventually times out. I'm trying to get to the output, but wildfly is throwing a fatal error. I think you are right about the JDBC connection- I ran the command it it shows that it is connected via an SSL

I am currently trying to stand up the application on a Docker instance, and it seems to run fine on the terminal. However, I get timed out when I try to access 172:20.128.3/cms/login. 

Thank you again so much for your help.

**Comment by jasonaowen** [comment]
You're very welcome!

Our Docker configuration is in flux right now; @mbestavros has been bringing it up-to-date with PR #868, but that work isn't quite finished yet. If you're going off the Docker configuration that's in master, I would expect it not to work.

Is Docker essential to what you're doing? If so, you might try the branch in #868, and report how well it works in that PR. If not, I suggest using a basic VM, or running everything in the host environment (which is what most of the contributors are doing right now). I've found that Docker can complicate things, and our project is somewhat complicated already, so it might be better to get something working first just to make sure all the pieces fit together.

Is that enough to get you unblocked, @Ylowe ?

**Comment by mbestavros** [comment]
@Ylowe From my experience, the Docker config present in master is broken; I wouldn't count on that getting you anywhere. As @jasonaowen mentioned, I've been working on improving the PSM's Docker configuration; you can check out my PR at #868. @slifty says that work should be merged soon.

**Comment by jasonaowen** [comment]
In #994, @Ylowe wrote:

> Set up wildfly and psm in /opt, and when ./gradlew db:update is run, it gets stuck at this output:

```
> Task :db:update
liquibase-plugin: Running the 'main' activity...
<------------> 0% EXECUTING [time]
> :db:update
```

> Could it be a problem with my gradle.properties? It is structured as so:

```
systemProp.databaseUser=psm
systemProp.databasePassword=psm
systemProp.databasePath=jdbc:postgresql://psm.scioutfit.com:9990/psm
```

> Any help would be appreciated. Running Ubuntu 14.

**Comment by jasonaowen** [comment]
@Ylowe, my suspicion is that you are having trouble connecting to your database. Let's try to confirm or deny that hypothesis.

Please run the follow command from the machine you're trying to run `./gradlew db:update` from:

```
psql --host=psm.scioutfit.com --port=9990 --username=psm psm
```

(I took the host, port, username, and database name in the above command from the `gradle.properties` you posted.)

Success would look like an interactive psql prompt, like this for example:

```
psql (10.4 (Ubuntu 10.4-2.pgdg16.04+1))
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

psm=> 
```

(The version numbers and connection details may differ, of course.)

Failure can take a number of different forms, which will hopefully contain clear error codes.

Either way, please paste the output of the above command, in its entirety, into this issue. That way, I'll be able to better understand what is going wrong and help you get the PSM deployed. Thanks!

**Comment by slifty** [comment]
I wanted to add a note here to point out that the updated docker build has been merged; please give this another try, following the instructions in DOCKER.md

**Comment by jasonaowen** [comment]
Hi @Ylowe,

We haven't heard from you in a few weeks. I hope that means you were able to get everything working!

If that's not the case, please reopen this issue, and we'll help you troubleshoot further.
