### ISSUE TITLE
./gradlew db:update frozen at 0%

### ISSUE THREAD

**Issue by Ylowe** [SolutionGuidance/psm#994]
Set up wildfly and psm in /opt, and when ./gradlew db:update is run, it gets stuck at this output:

> Task :db:update
liquibase-plugin: Running the 'main' activity...
<------------> 0% EXECUTING [time]
> :db:update

Could it be a problem with my gradle.properties? It is structured as so:

systemProp.databaseUser=psm
systemProp.databasePassword=psm
systemProp.databasePath=jdbc:postgresql://psm.scioutfit.com:9990/psm

Any help would be appreciated. Running Ubuntu 14.

**Comment by jasonaowen** [comment]
Hi @Ylowe, I'm going to merge this into #985, and we can continue the conversation there.

**Comment by jasonaowen** [comment]
Duplicate of #985
